name: Auto Commit

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  git-auto-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Git commit
      id: "auto-commit-action"
      uses: ./
