name: Notify on Slack

on:
  pull_request:
    branches: [ master ]
jobs:
  slackNotify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        GITHUB_ACTIONS_BOT: ${{ secrets.GITHUB_ACTIONS_BOT }}
