

name: FirstMessage
# Message displayed to the user when they first join
on: [pull_request_target, issues]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Hello'
        default: 'cake'
        # Input has to be provided for the workflow to run
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "firstGreetings"
  firstGreeting:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    # Represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Greeter"
      # Once a greeting code against the code base 
        uses: actions/first-interaction@v1
        with:
        # Secret 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          greeting: " Hello **#**, Welcome to the repo of We Tried :) "
          # Greeting Message 
          issue-message: 'New pull request'
