

name: FirstMessage
# Message displayed to the user when they first join
on: [pull_request]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "firstGreetings"
  firstGreeting:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Greeter"
      # Once a greeting code against the code base 
        uses: JJ/pr-greeting-action@releases/v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          greeting: "Hey **#** welcome to this repo"
