

name: FirstMessage
# Message displayed to the user when they first join
on: [pull_request_target, issues]


jobs:
# This workflow contains a single job called "firstGreetings"
  firstGreeting:
  # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: FirstWelcome
    permissions:
      pull-requests: write
      issues: write
    # Represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Greeter"
      # Once a greeting code against the code base 
        uses: actions/first-interaction@v1
        with:
        # Secret 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          greeting: " Hello **#**, Welcome to the repo of We Tried :) "
          # Greeting Message 
          issue-message: 'New pull request'
